// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 5/2/2026, 12:30:21 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/tonio/projects/bijoux-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/plugins/**/*.{js,ts,mjs}","/Users/tonio/projects/bijoux-site/composables/**/*.{js,ts,mjs}","/Users/tonio/projects/bijoux-site/utils/**/*.{js,ts,mjs}","/Users/tonio/projects/bijoux-site/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tonio/projects/bijoux-site/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;